### ISSUE TITLE
UI Shell: Experimental Release

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/issue-tracking#1]
The design, documentation and development of the Common UI shell.

## Stories

- As an IBM designer, I can learn more about Carbon’s approach to page layout and how to structure an app using their UI Shell components
- As an IBM offering manager, I can understand what the impact of the UI Shell work is to my offering’s roadmap
- As an IBM developer, I can learn how to enable the UI Shell and use the corresponding styles and components from `carbon-components` and `carbon-components-react`

### Projects

- Components
  - [ ] Platform Header
    - [x] Design
    - [x] Development - Styles
    - [ ] Development - Vanilla
    - [ ] Development - React.js
    - [ ] Development - Spec
    - [ ] Platform Left Navigation Menu
      - [x] Design
      - [x] Development - Styles
      - [ ] Development - Vanilla
      - [ ] Development - React.js
      - [ ] Development - Spec
    - [ ] Search bar
      - [ ] Design
      - [ ] Development - Styles
      - [ ] Development - Vanilla
      - [ ] Development - React.js
      - [ ] Development - Spec
  - [ ] Platform Side Navigation
    - [x] Design
    - [x] Development - Styles
    - [ ] Development - Vanilla
    - [ ] Development - React.js
    - [ ] Development - Spec
  - [ ] Panels
    - [ ] Global Product Switcher
      - [x] Design
      - [ ] Development - Styles
      - [ ] Development - Vanilla
      - [ ] Development - React.js
      - [ ] Development - Spec
    - [ ] Notification Panel
      - [ ] Design
      - [ ] Development - Styles
      - [ ] Development - Vanilla
      - [ ] Development - React.js
      - [ ] Development - Spec
    - [ ] Profile Panel
      - [ ] Design
      - [ ] Development - Styles
      - [ ] Development - Vanilla
      - [ ] Development - React.js
      - [ ] Development - Spec
    - [ ] Account Switcher
      - [ ] Design
      - [ ] Development - Styles
      - [ ] Development - Vanilla
      - [ ] Development - React.js
      - [ ] Development - Spec
- [ ] Education & Activation, Communication
  - [ ] Blog post detailing why we are making a UI Shell
  - [ ] Developer documentation for helping folks use the UI Shell
  - [ ] Design documentation around UI Shell

## Deliverables

- Design
  - Box folder: https://ibm.ent.box.com/folder/50033696944
- Development
- Artifacts
- Content
