### ISSUE TITLE
Curriculum for Carbon dual Track Coursework

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/issue-tracking#120]
Create coursework for June Patterns cohort that consists of:

combined: about Design Language
combined: the IBM Design Language (Grid, color, type, motion)
combined: about Design Systems
combined: the IBM Design System (Language, design Tooling, Code Tooling, Outreach)

then split tracks:
design: setting up Sketch Environment, working with the Sketch Toolkit
FED: setting up, basics

Design: design tooling Exercise
FED: code exercise

much of the materials should be sourced/consolidated from existing Design Essentials, Carbon Design Training, and @mattrosno's FED coursework.

Will form the Basis for general coursework for product teams, where the variability is mostly the exercises.

**Comment by jeanservaas** [comment]
## Carbon Patterns Coursework

Keynote file:
https://ibm.box.com/s/uhzy7z2tbks2s6dcv9xjrk23ohhrc13a

<br>

**The work represented here:**

- [x] Consolidate, trim down and refresh IBM Design Essentials materials with an eye towards relevancy to Product

<br>

_Note: I did not include motion content and I did not incorporate the Essentials course on the Design kit since most of what @aagonzales and Erica covered had to do with box drive which is now irrelevant._

<br>

**Still needs to be done:**

- [ ] **Create exercises:** Need to make this content more interactive for a workshop format; where / how do we want to add break out sessions or activities

- [ ] Add "Set up Sketch environment" / kit and symbol intro content 

- [ ] How will we incorporate "Code tooling" content? @mattrosno 's Dev Essentials content is not represented here

- [ ] Is there more we want to say about Patterns, Add ons, the contribution model and Carbon governance?

**Comment by jeanservaas** [comment]
work captured in:
https://github.com/carbon-design-system/issue-tracking/issues/114

**Comment by chrisconnors-ibm** [comment]
The framework we're using for the day one schedule:

1 hour (lecture, all participants) 15 minutes "What's a Design Language", 45 minutes "The IBM Design Language"

_break_

1 hour (lecture, all participants) 15 minutes "What's a Design System", 45 minutes "The IBM Design System"

_lunch_

**Design/Research Track**
1 hour (lecture + lab) "Sketch Intro (depending on Audience) and Setting up the Carbon Sketch libraries" + Some basics (using the templates, using our symbols, etc.)
**Developer Track**
1 hour (lecture + lab) "Setting up the Carbon Development Environment"

_break_

**Exercises***

***interns/college campuses/EHP:** 
Design: Select a well known product or service (ie AirBnB, VRBO, Netflix, etc) and express it in the IBM Design Language using the Sketch Libraries.

Development: There are a series of exercises we'll repurpose from the Dev Essentials Tutorials that @mattrosno et al have authored

**IBM Product Teams**
Design: Start applying the IBM Design Language to existing products
Development: Migrate existing products to Carbon v10 based on those designs

(If we wanted to do a contribution primer, when would that fit in?)
