### ISSUE TITLE
UX Improvements to Icons Library

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/issue-tracking#44]
Our icons library is limited when it comes to searching for icons and gaining more context around any individual icon.

Proposed new user stories:

- [ ] As a user, I can search for an icon by relevant terms (synonyms, etc.) that are not the same as the icon name
- [ ] As a user, I can learn more about the proper use of any given icon by consuming structured metadata about that icon
- [ ] As a user, I can see links to other icons related to any given icon

- [ ] As a contributor, I can include structured metadata along with my icon, including suggested use, alternate keywords, original designer, and other relevant information about the intent and actual usage of the icon

**Comment by claycrenshaw** [comment]
@chrisconnors-ibm @joshblack

**Comment by designertyler** [comment]
Here's a list of the most commonly searched terms on the site. This should help figure out which popular terms are not showing any results and what to use for alternate meta data tags. https://ibm.box.com/s/lsohvlh5e8xxx8u1vxx2lhfzd0kazn7o

**Comment by designertyler** [comment]
Closing in place of the cupcake, birthday, wedding cake issues https://github.com/carbon-design-system/carbon-website/issues/1485
