### ISSUE TITLE
❄ Sprint 23  “The one where things get icy” ❄

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/issue-tracking#54]
### Elements 
https://github.com/IBM/carbon-elements/issues/47
- Type
- Color
- Layout
- Grid
- Icons
- Motion 

### Website
**V10 Updates**
- Next/Prev component - @lovemecomputer   https://github.com/carbon-design-system/carbon-website/issues/305 	
- Do/Don’t component - @lovemecomputer https://github.com/carbon-design-system/carbon-website/issues/354
- Update page template - @alisonjoseph   https://github.com/carbon-design-system/carbon-website/issues/303
- Bring in Elements (typography, grid, layout) _if ready this sprint_

### Components
Update prefix  - https://github.com/carbon-design-system/issue-tracking/issues/53

**Experimental Components** - @aledavila / @tw15egan / @jnm2377
- [x] Inline Loading 
- [ ] Loading 
- [ ] Overflow Menu 
- [x] Tabs
- [ ] Search
- [x] File Uploader
- [ ] Progress Bar
- [ ] Modal
- [x] Code Snippet
- [x] Textarea

Accessibility - @dakahn
- AVT1 Audits on new components
- AVT1 Internal guidance/documentation
- Port merged accessibility PRs to the React codebase
- Accessibility Bug Fixes
  - [ ] https://github.com/IBM/carbon-components/issues/1364
  - [ ] https://github.com/IBM/carbon-components/issues/1363
  - [ ] https://github.com/IBM/carbon-components/issues/1362
  - [ ] https://github.com/IBM/carbon-components/issues/1361
  - [ ] https://github.com/IBM/carbon-components/issues/1351
  - [ ] https://github.com/IBM/carbon-components/issues/1347
  - [ ] https://github.com/IBM/carbon-components/issues/1346
  - [ ] https://github.com/IBM/carbon-components/issues/1345
  - [ ] https://github.com/IBM/carbon-components/issues/1342
  - [ ] https://github.com/IBM/carbon-components/issues/1341
  - [ ] https://github.com/IBM/carbon-components/issues/1330
  - [ ] https://github.com/IBM/carbon-components/issues/1317

**Experimental React** - @emyarod
 https://github.com/IBM/carbon-components-react/issues/1512
- [x] Tag 
- [x] Structured List 
- [x] Notification 

**UI Shell**
- Vanilla JS - @asudoh / @emyarod
  - Header https://github.com/IBM/carbon-components/issues/1355
    - Menu? https://github.com/IBM/carbon-components/issues/1358
  - Side Nav https://github.com/IBM/carbon-components/issues/1356
  - Panels https://github.com/IBM/carbon-components/issues/1359
- React @joshblack
  - Side Nav https://github.com/IBM/carbon-components-react/issues/1414
  - Menu https://github.com/IBM/carbon-components-react/issues/1413
  - Panels https://github.com/IBM/carbon-components-react/issues/1411
- Styles/Markup @joshblack 
  - Panels

### Elements 
https://github.com/IBM/carbon-elements/issues/47

- [ ] Spacing Tokens - https://github.com/IBM/carbon-elements/issues/54
- [ ] Vertical Spacing Type Styles - https://github.com/IBM/carbon-elements/issues/29
- [ ] Interaction Colors for Elements - https://github.com/IBM/carbon-elements/issues/12
- [ ] Finalize Color Tokens - https://github.com/IBM/carbon-elements/issues/53
- [ ] Icon Strategy - https://github.com/IBM/carbon-elements/issues/10
- [ ] Update Type Styles based on Usage - https://github.com/IBM/carbon-elements/issues/55

### Website
**V10 Updates**
- [ ] Page Layout - https://github.com/carbon-design-system/carbon-website/issues/303
- [ ] Site Feedback - https://github.com/carbon-design-system/carbon-website/issues/56
- [ ] Homepage Design - https://github.com/carbon-design-system/carbon-website/issues/292
- [ ] Component Examples - https://github.com/carbon-design-system/carbon-website/issues/230
- [ ] Usage Content for Accordion - https://github.com/carbon-design-system/carbon-website/issues/358
- [ ] Usage Content for Experimental Icons - https://github.com/carbon-design-system/carbon-website/issues/160
 
### Experimental Components
- [ ] Pagination - https://github.com/IBM/carbon-components/issues/1251
- [ ] Component Error States - https://github.com/IBM/carbon-components/issues/1390
- [ ] Data Table - https://github.com/IBM/carbon-components/issues/1246
- [ ] Motion Audit - https://github.com/IBM/carbon-elements/issues/56
