### ISSUE TITLE
Open Source `duo-monorepo` under IBM/carbon-elements

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/issue-tracking#6]
This Epic is to help plan how we're going to release the IBM Design Language (duo) elements under the IBM organization. The existing work for duo elements is located under: https://github.ibm.com/carbon/duo-monorepo.

The current proposal is the following:

- Create a GitHub repo under the IBM org called `carbon-elements`
- Phase in the different elements packages in the following order:
  - [ ] Icons `@carbon/icons`
  - [x] Icons react `@carbon/icons-react`
  - [ ] Motion `@carbon/motion`
  - [ ] Colors `@carbon/colors`
  - [ ] Typography `@carbon/type`
  - [ ] Grid `@carbon/grid`
- Signal to folks in #duo-dev about our plans to migrate to the public `@carbon` scope for the various packages
- Continue support for a duo-monorepo package 1 month after publishing package to public NPM

### FAQ

- Why are we calling this `carbon-elements`?
  - These packages will be used to distribute assets to software-based products. Since Carbon will be leading the charge for these types of products, we will release these specific assets under that umbrella.

**Comment by alisonjoseph** [comment]
closing in favor of https://github.com/IBM/carbon-elements/issues/47
