### ISSUE TITLE
Using new Design Language color palette

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/issue-tracking#8]
This epic will hold all of the issues necessary for introducing the new experimental color palette to the  Design System. It will contain references for work for offering management, design, and engineering.

It also attempts to capture the user stories we're addressing.

#### Stories

- As an IBMer, I can visit a page on the Carbon website that explains what the experimental label means for my offering/team/product.
- As an IBM designer, I can download the experimental sketch library and use it to explore and use the new color palette
- As an IBM developer, I can discover how to quickly enable experimental colors in carbon-components
- As an IBM developer, I can install carbon-colors and get the experimental colors that I want to try out by following accessible documentation

  - Reference links:
    - https://duo-staging.w3ibm.mybluemix.net/elements/color-palette/
    - https://duo-staging.w3ibm.mybluemix.net/elements/color-ui/

#### Process

- [x] Experimental colors proposed
- [ ] [Experimental colors is evaluated from a design perspective](https://github.com/IBM/carbon-elements/issues/12)
- [ ] [Experimental color design spec is delivered through a Sketch file under a Box link](https://github.com/IBM/carbon-design-kit/issues/51)
- [ ] Experimental color development work begins
- [ ] When work is complete, development adds a design reviewer to verify work through a staging link
- [ ] Experimental color is available as a theme
- [ ] Website
  - [x] [Documentation around experimental label](https://github.com/carbon-design-system/carbon-website-gatsby/pull/38)
  - [ ] Documentation around how to enable experimental colors
    - [ ] In vanilla `carbon-colors`
