### ISSUE TITLE
Sprint 4: The gang gets audited 🔍

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/issue-tracking#90]
## Sprint Focus:

- [ ] Components
  - [x] Continue performing audits and prioritize bug fixes
  - [x] Track progress of components to stable #91
    - Submit group of components to @kuehndaniel for external a11y audit
  - [x] Document public Sass API in v10 https://github.com/IBM/carbon-components/issues/1856
    - @jnm2377 scheduled
  - [x] Elements
    - [X] ~Integrate type styles in components https://github.com/IBM/carbon-components/issues/1546~
    - [x] ~Integrate font face in components styles https://github.com/IBM/carbon-components/issues/1857~
    - [x] Integrate motion in components https://github.com/IBM/carbon-components/issues/1433
  - [ ] Accessibility
    - [ ] DropdownV2 and associated ListBox https://github.com/IBM/carbon-components/issues/1147
    - [ ] Date Picker https://github.com/IBM/carbon-components-react/issues/1899
- [x] Migration
  - [x] Verify `migrate-to-10.x.md` documents are up-to-date
    - Meeting scheduled for 2/25 for working session
  - [x] Research with teams looking to migrate
    - On-going in: https://ibm.box.com/s/vfrnt80ycioz53gba2grmfgtr6oghtm5
- **Website**: _work is slightly de-prioritized as we finish up component implementations_
  - [ ] Website Grid (potentially related to UI Shell): https://github.com/carbon-design-system/carbon-website/issues/1091
  - [ ] MDX conversion https://github.com/carbon-design-system/carbon-website/pull/1135
  - [ ] Top nav tabs stacking (in progress) https://github.com/carbon-design-system/carbon-website/issues/578
  - bugs & fixes 
  - **update/add to this list after Wednesday dev meeting**

## De-prioritized updates

- UI Shell: we are keeping UI Shell work experimental for v10 launch, and will re-focus on this work post-v10 
- Component Page re-design https://github.com/carbon-design-system/carbon-website/issues/407
- Codepen links
  - Wait till components are stable and update pre-release
