### ISSUE TITLE
v10 Migration Content

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/issue-tracking#98]
- [ ] Elements
  - [x] [Color](https://github.com/IBM/carbon-elements/blob/master/docs/migration/10.x-color.md)
  - [x] [Type](https://github.com/IBM/carbon-elements/blob/master/docs/migration/10.x-type.md)
  - [x] Layout https://github.com/ibm/carbon-elements/issues/271
  - [x] Motion https://github.com/IBM/carbon-elements/issues/398
  - [ ] Icons
    - [ ] Deprecate `carbon-icons`
    - [ ] Add migration guide
    - [x] [Add migration table](https://github.com/IBM/carbon-elements/blob/master/docs/migration/10.x-icons.md)
  - [ ] Themes ???
- [ ] Components
  - [ ] Vanilla
    - [ ] Create draft CHANGELOG.md file for release https://github.com/IBM/carbon-components/issues/2033
    - [x] Create entrypoint at `docs/migration/migrate-to-10.x.md` https://github.com/IBM/carbon-components/issues/2034
    - [ ] Include public Sass API https://github.com/IBM/carbon-components/issues/1856
    - [ ] Clear out TODOs in migration docs
  - [ ] React
    - [ ] Create draft CHANGELOG.md file for release https://github.com/IBM/carbon-components-react/issues/1991
    - [x] Create entrypoint at `docs/migration/migrate-to-10.x.md` https://github.com/IBM/carbon-components-react/issues/1992
- [ ] Tools, `carbon-upgrade`
  - [ ] Write migration tool for `carbon-icons`
    - [ ] Vanilla
    - [ ] React
- [ ] Website
  - How do we link out to migration content from the homepage?
